db_asset_bundle_sample:
  target: dev
  outputs:
    dev:
      type: databricks
      schema: default
      host: ${{ secrets.DATABRICKS_HOST }}
      http_path: ${{ secrets.DATABRICKS_HTTP_PATH }}
      token: ${{ secrets.DATABRICKS_TOKEN }}
      threads: 4