name: Run dbt Models on Databricks

on:
  workflow_dispatch:  # allow manual trigger
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-dbt:
    name: Execute dbt Models on Databricks
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt Core + Databricks adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-databricks

      - name: Verify dbt installation
        run: dbt --version

      # Set DBT_PROFILES_DIR to point to your profiles directory
      - name: Set environment variable for dbt profiles
        run: echo "DBT_PROFILES_DIR=${{ github.workspace }}/profiles" >> $GITHUB_ENV

      - name: Run dbt deps
        run: dbt deps

      - name: Validate dbt connection
        run: dbt debug --target databricks

      - name: Run dbt models
        run: dbt run --target databricks

      - name: Run dbt tests
        run: dbt test --target databricks