db_asset_bundle_sample:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: workspace
      schema: dbt_test
      #auth_type: oauth
      #host: "{{ env_var('DATABRICKS_HOST') }}"
      #client_id: "{{ env_var('DATABRICKS_CLIENT_ID') }}"
      #http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      #client_secret: "{{ env_var('DATABRICKS_CLIENT_SECRET') }}"
      method: http
      http_path: /sql/1.0/warehouses/735e65862e3dd931
      host: "{{ env_var('DBT_HOST') }}"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      threads: 4